"""M3Resp public API."""

from m3resp import io
from m3resp.core.session import M3Session
from m3resp.data import (
    BreathEvent,
    Event,
    EventData,
    Interval,
    IntervalData,
    IntervalDataCollection,
    LinkedBreath,
    ParameterResult,
    ParameterResultCollection,
    PixelMap,
    PixelMask,
    PixelMaskCollection,
    ProcessingHistory,
    ProcessingStep,
    QualityFlag,
    QualityReport,
    Signal,
    SignalCollection,
    TimeSeries,
    coerce_breath_event,
    coerce_breath_events,
    coerce_event,
    coerce_interval,
    coerce_intervals,
    event_to_dict,
)
from m3resp.datamodel import (
    Case,
    ClinicalEvent,
    DataFile,
    DataModelRecorder,
    DataModelStore,
    DerivedFeature,
    Device,
    ProcessingRun,
    QualityAnnotation,
    RecordingSession,
    SignalStream,
    export_store,
    validate_store,
)
from m3resp.presets import (
    EITPreset,
    EMGPreset,
    MultimodalPreset,
    Preset,
    available_presets,
    get_preset,
    register_preset,
)
from m3resp.synchronization import (
    compute_offsets_from_timestamps,
    link_breaths_by_time,
    resample_signal,
)
from m3resp.workflows import (
    WorkflowResult,
    available_steps,
    load_spec,
    register_step,
    run_spec,
    run_workflow,
)

__version__ = "0.2.0"

__all__ = [
    "BreathEvent",
    "Case",
    "ClinicalEvent",
    "DataFile",
    "DataModelRecorder",
    "DataModelStore",
    "DerivedFeature",
    "Device",
    "EITPreset",
    "EMGPreset",
    "Event",
    "EventData",
    "Interval",
    "IntervalData",
    "IntervalDataCollection",
    "LinkedBreath",
    "M3Session",
    "MultimodalPreset",
    "ParameterResult",
    "ParameterResultCollection",
    "PixelMap",
    "PixelMask",
    "PixelMaskCollection",
    "Preset",
    "ProcessingHistory",
    "ProcessingRun",
    "ProcessingStep",
    "QualityAnnotation",
    "QualityFlag",
    "QualityReport",
    "RecordingSession",
    "Signal",
    "SignalCollection",
    "SignalStream",
    "TimeSeries",
    "WorkflowResult",
    "available_presets",
    "available_steps",
    "coerce_breath_event",
    "coerce_breath_events",
    "coerce_event",
    "coerce_interval",
    "coerce_intervals",
    "compute_offsets_from_timestamps",
    "event_to_dict",
    "export_store",
    "get_preset",
    "io",
    "link_breaths_by_time",
    "load_spec",
    "register_preset",
    "register_step",
    "resample_signal",
    "run_spec",
    "run_workflow",
    "validate_store",
]
