#!/usr/bin/env node
// Generates tools/mockup_tool/stage3_gui_mockup.html from src/**.
// No dependencies — Node built-ins only.
//
// The output is a thin shell: it links src/** via <link> and <script src>
// rather than inlining it, so editing a file under src/css/ or src/js/ takes
// effect on a plain browser reload with no rebuild. Only changes to
// src/html/** (which get inlined, since there is no way to link an HTML
// fragment over file://) require re-running this script.
//
// Nothing needs a server: the page uses classic scripts and never calls
// fetch(), so it opens by double-click over file://.
//
// Order matters: the tags are emitted in the exact order listed below. That
// ordering IS the module system here — there are no imports, just top-level
// declarations that later files read (EIT, REVIEW, ZOOM, savedSequences), so
// a new source file must be inserted where declaration-before-use still
// holds, not just alphabetically.

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'stage3_gui_mockup.html');

const TITLE = '<title>m3resp — Stage 3 GUI mockup</title>';

const CSS_FILES = [
  'css/base.css',
  'css/prepare.css',
  'css/prepare-eit.css',
  'css/prepare-vent.css',
  'css/prepare-slicer.css',
  'css/design.css',
  'css/popover.css',
  'css/results.css',
];

const HTML_FILES = [
  'html/shell.html',
  'html/prepare.html',
  'html/design.html',
  'html/check.html',
  'html/results.html',
];

const JS_FILES = [
  // data blobs first — the modules below reference them at top level
  'js/data/eit-frame-data.js',
  'js/data/review-figures.js',
  'js/core/tabs.js',
  'js/design/graph-data.js',
  'js/design/selection.js',
  'js/design/canvas-zoom.js',
  'js/design/node-drag.js',
  'js/design/palette-panel.js',
  'js/design/data-preview.js',
  'js/design/workflow-blocks.js',
  'js/design/connections.js',
  'js/prepare/signal-lanes.js',
  'js/prepare/window-slicer.js',
  'js/prepare/saved-sequences.js',
  'js/prepare/sidebar.js',
  'js/prepare/eit-workspace.js',
  'js/prepare/vent-stack.js',
  'js/prepare/emg-panel.js',
  'js/prepare/zoom-engine.js',
  'js/results/plots.js',
  'js/results/params-filter.js',
];

function read(relPath) {
  return fs.readFileSync(path.join(SRC, relPath), 'utf8');
}

function readTrimmed(relPath) {
  // Section files are cut at line boundaries, so each owns a trailing
  // newline; join without doubling blank lines.
  return read(relPath).replace(/\n$/, '');
}

function build() {
  const missing = [...CSS_FILES, ...HTML_FILES, ...JS_FILES]
    .filter(f => !fs.existsSync(path.join(SRC, f)));
  if (missing.length) {
    throw new Error(`build.js: listed but missing under src/: ${missing.join(', ')}`);
  }

  const out = [
    '<!-- GENERATED by build.js — edit files under src/, not this file.',
    '     CSS and JS are linked, so a browser reload picks those edits up',
    '     without a rebuild; re-run `node build.js` only after changing',
    '     src/html/**, or after adding/removing a source file. -->',
    TITLE,
    ...CSS_FILES.map(f => `<link rel="stylesheet" href="src/${f}">`),
    HTML_FILES.map(readTrimmed).join('\n'),
    ...JS_FILES.map(f => `<script src="src/${f}"></script>`),
    '',
  ].join('\n');

  fs.writeFileSync(OUT, out);
  console.log(
    `Built ${path.relative(ROOT, OUT)} ` +
    `(${(out.length / 1024).toFixed(0)} KB, ${out.split('\n').length} lines, ` +
    `${CSS_FILES.length + JS_FILES.length} linked files)`
  );
}

build();
