"""Stable, time-sortable identifier generation (data model doc Sec 3.4)."""

from __future__ import annotations

import os
import time
import uuid


def new_id(prefix: str | None = None) -> str:
    """Return a UUIDv7-style, time-sortable identifier.

    Python's stdlib ``uuid`` module gains ``uuid7`` in 3.14; this repo targets
    3.10+, so the version bits are generated by hand from a millisecond
    timestamp plus random bytes (RFC 9562 layout) rather than adding a
    dependency for one function.
    """

    unix_ms = int(time.time() * 1000)
    rand = os.urandom(10)

    time_hi = (unix_ms >> 16) & 0xFFFFFFFF
    time_lo = unix_ms & 0xFFFF

    rand_a = ((rand[0] << 8) | rand[1]) & 0x0FFF
    rand_b = int.from_bytes(rand[2:10], "big") & 0x3FFFFFFFFFFFFFFF

    value = (time_hi << 96) | (time_lo << 80)
    value |= (0x7 << 76) | (rand_a << 64)
    value |= (0x2 << 62) | rand_b

    identifier = str(uuid.UUID(int=value))
    return f"{prefix}_{identifier}" if prefix else identifier
